var readlineSync = require('readline-sync');
var pet = {};
var name = readlineSync.question('Your pet name: ');
pet.name = name;
var gender = readlineSync.question('Pet gender (Male/Female): ');
pet.gender = gender;
var age = readlineSync.question('Pet age: ');
pet.age = parseInt(age);
var weight = readlineSync.question('Pet weight: ');
pet.weight = parseInt(weight);
console.log(pet);